name: Build and push latest e2e image to Docker Hub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ./actions
          repository: AnhNg-GithubActions/e2e
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: ./actions/.github/actions/build-e2e-image
        with:
          tag: latest
          docker-hub-user: ${{ secrets.DOCKER_HUB_USER }}
          docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          docker-hub-address: anhnguyen104
